- name: install bellow services
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.service:
      name: "{{item}}"
      state: present
    loop:
    - ansible
    - nginx
    - mysql
    - postfix
