- name: loops demo
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: 
    - { Name: 'mysql',state: 'present' }
    - { Name: 'nginx', state: 'obsent' }
    - { Name: 'postfix',state: 'present' }
    - { Name: 'nginx',state: 'present' }
