- name: loops demo
  hosts: web
  tasks: 
  - name: install packages 
    ansible.builtin.package:
      name: " {{ item.name }}"
      state: " {{ item.state }}" 
      enabled: yes 
    loop: 
    - { name: 'mysql', state: 'present' } 
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'present'}
    - { name: 'nginx', state: 'present'}