- name: demo on filters/functions
  hosts: web 
  vars:
    GREETING: HELLO star
    NUM: [1,2,2,3,4,5,5]
  tasks: 
  - name: print the default variables 
    ansible.builtin.debug: 
      msg: " Hello {{ COURSE | default('ansible')}}"

  - name: print lowercase 
    ansible.builtin.debug: 
      msg: "{{GREETING | lower}}"

  - name: print uppercase
    ansible.builtin.debug: 
      msg: "{{GREETING | upper}}"    

  - name: get the unique value 
    ansible.builtin.debug: 
      msg: "{{NUM | unique}}"    

  - name: get the min and max values 
    ansible.builtin.debug:
      msg: " Min: {{NUM | min}}, Max: {{NUM | max}}"  

  - name: convert map to list
    vars: 
      course: 
        name: Devops
        trainer: sive 
        duration: 120hrs
    ansible.builtin.debug: 
      msg: "{{course | dict2items}}"    

  - name: list to map
    vars: 
      course: 
      - {"key": "name", "value": "Devops"}
      - {"key": "tariner", "value": "siva"}
      - {"key": "duration", "value": "120hrs"}
    ansible.builtin.debug: 
      msg: "{{course | items2dict}}"  
